name: Clippy check

on: pull_request

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal --no-self-update
      - uses: Swatinem/rust-cache@v2.7.7
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - name: Set up git config
        run: |-
          git config --global user.name Test && \
          git config --global user.email test@test.com
      - name: Run Tests
        run: cargo test
